project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "info/**/*.md"    # inclui os MD da pasta info/

website:
  title: "Mestre 2 — Jogo de Perguntas e Respostas"
  site-url: "https://pedrochaim.github.io/mestre2/"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Regras"
        href: regras.qmd
      - text: "Dicionário"
        href: dicionario_temas_subtemas.md
      - text: "Instruções"
        menu:
          - text: "Microsubtemas"
            href: info/instrucoes_geracao_microsubtemas.md
          - text: "Perguntas"
            href: info/instrucoes_geracao_perguntas.md
