project:
  type: website
  resources: 
    - "info/"  # <- inclui os arquivos de instruções na pasta info
  output-dir: docs   # <- aqui você fixa a pasta de saída
  render:
    - "*.qmd"
    - "info/**/*.md"    # inclui os MD da pasta info/    - "!docs/**"   # nunca render a pasta de saída

website:
  title: "Mestre 2 — Jogo de Perguntas e Respostas"
  site-url: "https://pedrochaim.github.io/mestre2/"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Regras"
        href: info/regras.md
      - text: "Dicionário"
        href: info/dicionario_temas_subtemas.md
      - text: "Instruções"
        menu:
          - text: "Microsubtemas"
            href: info/instrucoes_geracao_microsubtemas.md
          - text: "Perguntas"
            href: info/instrucoes_geracao_perguntas.md